version: 2
jobs:
  build:
    working_directory: ~/canvas-lms
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm jest
