version: 2
jobs:
  build:
    working_directory: ~/canvas-lms
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Test application
          command: |
              TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split --split-by=timings)
              yarn test $TEST
